import { describe, expect, it } from 'vitest';
import {
  buildIncidentReport,
  buildMockDataset,
  incidentDetailSchema,
  isWithinWindow,
  resolveTimeWindow,
} from '../src';

const NOW = new Date('2026-09-12T12:00:00.000Z');

describe('mock dataset', () => {
  const dataset = buildMockDataset(NOW);

  it('provides 15 incidents', () => {
    expect(dataset).toHaveLength(15);
  });

  it('validates against the incident schema', () => {
    for (const incident of dataset) {
      expect(() => incidentDetailSchema.parse(incident)).not.toThrow();
    }
  });

  it('flags every record and every article as mock', () => {
    expect(dataset.every((incident) => incident.isMock)).toBe(true);
    expect(dataset.every((incident) => incident.articles.every((article) => article.provider === 'mock'))).toBe(true);
  });

  it('keeps all mock incidents inside the default 30-day window', () => {
    const window = resolveTimeWindow('last_30_days', NOW);
    expect(dataset.every((incident) => isWithinWindow(incident.incidentDate, window))).toBe(true);
  });

  it('uses only non-resolving example domains', () => {
    const urls = dataset.flatMap((incident) => incident.articles.map((article) => article.originalUrl));
    expect(urls.every((url) => /https:\/\/[a-z.]*example\.(com|org|gov)\//.test(url))).toBe(true);
  });

  it('covers the required event classes', () => {
    const types = new Set(dataset.map((incident) => incident.incidentType));
    for (const required of [
      'fire',
      'well_control',
      'well_integrity',
      'equipment_failure',
      'pipeline_rupture',
      'explosion',
      'gas_leak',
      'loss_of_containment',
      'oil_spill',
      'evacuation',
      'blowout',
    ]) {
      expect(types).toContain(required);
    }
  });

  it('groups multiple sources under one incident', () => {
    const multiSource = dataset.filter((incident) => incident.articles.length > 1);
    expect(multiSource.length).toBeGreaterThanOrEqual(10);
    const fire = dataset.find((incident) => incident.id === 'mock-incident-offshore-fire-northstar');
    expect(fire?.articles).toHaveLength(4);
    expect(fire?.sourceCount).toBe(4);
    expect(new Set(fire?.articles.map((article) => article.publisher)).size).toBe(4);
  });

  it('never reports an unknown consequence as zero', () => {
    const wellIntegrity = dataset.find((incident) => incident.id === 'mock-incident-well-integrity-annulus');
    expect(wellIntegrity?.consequences.missingPersons).toBeNull();
  });
});

describe('PDF report model', () => {
  const dataset = buildMockDataset(NOW);
  const incident = dataset.find((item) => item.id === 'mock-incident-refinery-explosion-helios');

  it('builds the full report structure', () => {
    expect(incident).toBeDefined();
    const report = buildIncidentReport(incident!, NOW);
    expect(report.documentTitle).toBe('OIL & GAS INCIDENT INTELLIGENCE REPORT');
    expect(report.highlights.length).toBeGreaterThanOrEqual(4);
    expect(report.highlights.length).toBeLessThanOrEqual(8);
    expect(report.sources).toHaveLength(5);
    expect(report.sources[0]?.index).toBe(1);
    expect(report.disclaimer).toContain('verified against the original sources');
    expect(report.footer).toBe('Generated by Oil & Gas Incident Intelligence');
  });

  it('labels severity as system-assessed', () => {
    const report = buildIncidentReport(incident!, NOW);
    const severity = report.assessment.find((row) => row.label === 'Severity');
    expect(severity?.value).toContain('System-assessed severity');
  });

  it('orders sources by tier, official first', () => {
    const report = buildIncidentReport(incident!, NOW);
    expect(report.sources[0]?.tier).toContain('Tier 1');
  });

  it('renders unreported consequences as "Not reported", never 0', () => {
    const report = buildIncidentReport(incident!, NOW);
    const missing = report.consequences.find((row) => row.label === 'Missing');
    expect(missing?.value).toBe('Not reported');
    expect(missing?.known).toBe(false);
  });

  it('omits unknown optional overview rows', () => {
    const report = buildIncidentReport(incident!, NOW);
    expect(report.overview.some((row) => row.label === 'Well')).toBe(false);
    expect(report.overview.some((row) => row.label === 'Operator')).toBe(true);
  });
});
