import type { Glossary } from './types';

export const EN_GLOSSARY: Glossary = {
  language: 'en',
  industryTerms: [
    'oil', 'gas', 'petroleum', 'crude', 'hydrocarbon', 'oilfield', 'oil field',
    'offshore platform', 'oil platform', 'gas platform', 'production platform',
    'drilling rig', 'drill rig', 'drillship', 'jack-up', 'jackup', 'semi-submersible',
    'fpso', 'fso', 'wellhead', 'well', 'borehole', 'subsea', 'topside',
    'refinery', 'refining', 'petrochemical', 'gas plant', 'gas processing',
    'lng', 'lng terminal', 'lng carrier', 'liquefied natural gas',
    'pipeline', 'gas pipeline', 'oil pipeline', 'gathering system', 'compressor station',
    'oil terminal', 'gas terminal', 'tank farm', 'fuel storage', 'fuel depot',
    'upstream', 'midstream', 'downstream', 'e&p', 'exploration and production',
    'opec', 'petrobras', 'equinor', 'shell', 'bp', 'exxonmobil', 'chevron', 'totalenergies',
    'conocophillips', 'aramco', 'adnoc', 'eni', 'pemex', 'pdvsa', 'cnooc', 'sinopec',
    'occidental', 'apache', 'woodside', 'santos', 'ineos', 'harbour energy', 'ithaca energy',
    'transocean', 'valaris', 'noble corporation', 'seadrill', 'saipem', 'subsea7',
    'halliburton', 'schlumberger', 'slb', 'baker hughes', 'weatherford',
  ],
  eventTerms: [
    'incident', 'accident', 'event', 'failure', 'emergency', 'fire', 'blaze', 'explosion',
    'blast', 'leak', 'release', 'spill', 'shutdown', 'shut down', 'evacuation', 'evacuated',
    'blowout', 'kick', 'rupture', 'collision', 'capsize', 'sinking', 'collapse',
    'casualty', 'fatality', 'fatalities', 'killed', 'injured', 'injuries', 'missing',
    'investigation', 'enforcement', 'prohibition notice', 'improvement notice',
    'near miss', 'mayday', 'muster', 'gas detected', 'alarm',
    'crash', 'crashed', 'ditch', 'ditched', 'ditches', 'ditching', 'struck', 'grounded',
    'shut in', 'shut-in', 'down-manning', 'downmanned', 'medevac', 'spilled', 'spilt',
    // Past and continuous forms are listed explicitly rather than derived with a
    // generic "-ed/-ing" suffix rule: that rule would turn "fire" into "fired" and
    // file every executive dismissal at an oil company as a safety event.
    'released', 'releasing', 'leaked', 'leaking', 'exploded', 'exploding',
    'ignited', 'ignition', 'ruptured', 'rupturing', 'spilling', 'burned', 'burnt',
    'burning', 'collapsed', 'erupted', 'evacuating', 'shutting down', 'shut down',
  ],
  strongPhrases: [
    'loss of containment', 'loss of primary containment', 'hydrocarbon release',
    'well control incident', 'loss of well control', 'well integrity failure',
    'well barrier failure', 'primary barrier failure', 'secondary barrier failure',
    'bop failure', 'blowout preventer failure', 'christmas tree failure', 'wellhead failure',
    'sustained casing pressure', 'annulus pressure', 'uncontrolled release',
    'h2s release', 'hydrogen sulphide release', 'toxic gas release',
    'process safety event', 'major accident hazard', 'emergency shutdown',
    'platform fire', 'platform explosion', 'refinery fire', 'refinery explosion',
    'rig fire', 'pipeline rupture', 'pipeline explosion', 'oil spill', 'gas leak',
    'subsea leak', 'riser failure', 'flare incident', 'well blowout',
  ],
  assetTerms: [
    'offshore platform', 'oil platform', 'gas platform', 'production platform',
    'wellhead platform', 'drilling rig', 'drillship', 'jack-up rig', 'semi-submersible rig',
    'fpso', 'fso', 'tlp', 'spar', 'subsea installation', 'refinery', 'gas processing plant',
    'lng plant', 'lng terminal', 'oil terminal', 'pipeline', 'compressor station',
    'storage facility', 'tank farm', 'petrochemical plant',
  ],
  wellTerms: [
    'well control', 'well integrity', 'well barrier', 'blowout', 'kick', 'bop',
    'blowout preventer', 'christmas tree', 'xmas tree', 'wellhead', 'tubing', 'casing',
    'cement', 'packer', 'annulus', 'dhsv', 'scssv', 'downhole safety valve',
    'surface controlled subsurface safety valve', 'workover', 'well intervention',
    'plug and abandonment', 'p&a', 'completion', 'drilling', 'sidetrack', 'shut-in',
  ],
  searchPhrases: [
    '"offshore platform" fire', '"drilling rig" accident', '"oil platform" explosion',
    '"gas platform" leak', '"well control" incident', '"well integrity" incident',
    '"BOP failure"', 'blowout oil', '"hydrocarbon release" offshore',
    '"loss of containment" refinery', '"pipeline rupture" gas', '"pipeline explosion"',
    'FPSO incident', 'drillship incident', '"oil spill" platform', '"gas leak" refinery',
    '"refinery fire"', '"LNG terminal" incident', '"offshore" evacuation oil',
    '"production platform" shutdown', '"subsea" leak oil', '"well blowout"',
  ],
  exclusionTerms: [
    'coal mine', 'coal mining', 'gold mine', 'quarry',
    'airliner', 'passenger jet', 'airport runway',
    'car crash', 'road traffic collision', 'motorway pile-up', 'bus crash',
    'train derailment', 'railway crossing',
    'apartment fire', 'house fire', 'residential fire', 'shopping centre fire',
    'solar farm', 'wind farm', 'wind turbine', 'nuclear reactor', 'nuclear plant',
    'pharmaceutical plant', 'food processing plant', 'textile factory',
    'stock price', 'share price', 'quarterly earnings', 'dividend', 'merger agreement',
  ],
};
