import { describe, expect, it } from 'vitest';
import { buildIncidentReport, buildMockDataset, type IncidentDetail } from '@ogii/domain';
import { renderReportHtml } from '../src/pdf/report-html';

const NOW = new Date('2026-09-12T12:00:00.000Z');

function reportFor(id: string): { incident: IncidentDetail; html: string } {
  const incident = buildMockDataset(NOW).find((item) => item.id === id);
  if (incident === undefined) throw new Error(`missing mock incident ${id}`);
  return { incident, html: renderReportHtml(buildIncidentReport(incident, NOW)) };
}

describe('PDF report HTML', () => {
  const { incident, html } = reportFor('mock-incident-refinery-explosion-helios');

  it('renders every required section (brief section 41)', () => {
    for (const section of [
      'OIL &amp; GAS INCIDENT INTELLIGENCE REPORT',
      'Incident Overview',
      'Key Highlights',
      'Incident Summary',
      'Consequences',
      'Sources',
    ]) {
      expect(html).toContain(section);
    }
  });

  it('always carries the disclaimer and the footer', () => {
    expect(html).toContain('verified against the original sources');
    expect(html).toContain('Generated by Oil &amp; Gas Incident Intelligence');
  });

  it('labels severity as system-assessed rather than official', () => {
    expect(html).toContain('System-assessed severity');
  });

  it('lists every source with publisher, date, tier and URL', () => {
    for (const article of incident.articles) {
      expect(html).toContain(article.publisher.replace(/&/g, '&amp;'));
      expect(html).toContain(article.originalUrl);
    }
    expect(html).toContain('Tier 1');
  });

  it('renders unreported consequences as "Not reported", never as 0', () => {
    expect(html).toMatch(/<th>Missing<\/th>\s*<td class="unknown">Not reported<\/td>/);
    expect(html).not.toMatch(/<th>Missing<\/th>\s*<td[^>]*>0<\/td>/);
  });

  it('renders a reported zero as 0', () => {
    const { html: fireHtml } = reportFor('mock-incident-offshore-fire-northstar');
    expect(fireHtml).toMatch(/<th>Fatalities<\/th>\s*<td>0<\/td>/);
  });

  it('marks mock reports so they cannot be mistaken for real events', () => {
    expect(html).toContain('Mock data');
  });

  it('forces a light colour scheme: a print document must never inherit dark mode', () => {
    expect(html).toContain('color-scheme: light');
    expect(html).toContain('background: #ffffff');
  });

  it('escapes HTML in any field that came from a source', () => {
    const hostile: IncidentDetail = {
      ...incident,
      title: '<script>alert("xss")</script> & "quoted"',
      articles: [
        {
          ...incident.articles[0]!,
          publisher: '<img src=x onerror=alert(1)>',
          title: "O'Brien & <b>bold</b>",
        },
      ],
    };
    const escaped = renderReportHtml(buildIncidentReport(hostile, NOW));
    // The dangerous characters must be escaped; the words themselves survive as text.
    expect(escaped).not.toContain('<script>');
    expect(escaped).not.toContain('<img src=x');
    expect(escaped).toContain('&lt;script&gt;');
    expect(escaped).toContain('&lt;img src=x onerror=alert(1)&gt;');
    expect(escaped).toContain('&amp;');
  });

  it('is deterministic for a fixed clock', () => {
    expect(renderReportHtml(buildIncidentReport(incident, NOW))).toBe(html);
  });
});
